 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BusinessLModelLAyer.Salon;
import javax.swing.JOptionPane;

/**
 *
 * @author sixst
 */
public class frmSalones extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAulas
     */
    public frmSalones() {
        initComponents();
        jtSalones.setModel(new Salon().GetAllModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnActualizar = new javax.swing.JButton();
        btnNuevaAula = new javax.swing.JButton();
        btnModificarAula = new javax.swing.JButton();
        btnEliminarAula = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSalones = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Salones");
        setPreferredSize(new java.awt.Dimension(582, 469));

        jToolBar1.setRollover(true);

        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnNuevaAula.setText("Nuevo Salón");
        btnNuevaAula.setFocusable(false);
        btnNuevaAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaAula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevaAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaAulaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevaAula);

        btnModificarAula.setText("Modificar Salón");
        btnModificarAula.setFocusable(false);
        btnModificarAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarAula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAulaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificarAula);

        btnEliminarAula.setText("Eliminar Salón");
        btnEliminarAula.setFocusable(false);
        btnEliminarAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarAula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAulaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarAula);

        btnCerrar.setText("Cerrar");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);

        jtSalones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtSalones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        jtSalones.setModel(new Salon().GetAllModel());
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevaAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaAulaActionPerformed
        // TODO add your handling code here:
        frmNSalon obj = new frmNSalon();
        obj.setTitle("Nuevo Salón");
        obj.setModal(true);
        obj.setVisible(true);
        jtSalones.setModel(new Salon().GetAllModel());
    }//GEN-LAST:event_btnNuevaAulaActionPerformed

    private void btnModificarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAulaActionPerformed
        // TODO add your handling code here:
        if (jtSalones.getSelectedRow() >= 0) {
            int idAula = (int) jtSalones.getValueAt(jtSalones.getSelectedRow(), 0);
            frmMSalon obj = new frmMSalon(idAula);
            obj.setTitle("Modificar Salon");
            obj.setModal(true);
            obj.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona un registro");
        }
    }//GEN-LAST:event_btnModificarAulaActionPerformed

    private void btnEliminarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAulaActionPerformed
        // TODO add your handling code here:
        if (jtSalones.getSelectedRow() >= 0) {
            int idAula = (int) jtSalones.getValueAt(jtSalones.getSelectedRow(), 0);
            int validacion = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar el registro?");
            if (validacion == 0) {
                if (new Salon(idAula).Delete()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro eliminado correctamente!");
                    jtSalones.setModel(new Salon().GetAllModel());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un registro! ");
            }
        }
    }//GEN-LAST:event_btnEliminarAulaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarAula;
    private javax.swing.JButton btnModificarAula;
    private javax.swing.JButton btnNuevaAula;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtSalones;
    // End of variables declaration//GEN-END:variables
}
